apiVersion: extensions/v1
kind: Deployment
metadata:
  name: kafka-connector-deployment
spec:
  replicas: 3 # tells deployment to run 2 pods matching the template
template: # create pods using pod definition in this template
    metadata:
    labels:
        app: kafka-connector
    spec:
      containers:
      - image: farithjhg/kafka-connector
      name: kafka-connector
      ports:
        containerPort: 8090
